name: Deploy a hot-upgrade package/version to AWS

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string

env:
  MIX_ENV: prod

jobs:
  build:
    name: Building a release and version file
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup BEAM
        uses: erlef/setup-beam@v1
        with:
          version-file: .tool-versions
          version-type: strict

      - name: Retrieve the deployed current.json
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "sa-east-1"
          source: "s3://calori-${{ secrets.CLOUD_ENV_NAME }}-distribution/versions/calori/${{ secrets.CLOUD_ENV_NAME }}/current.json"
          dest: "./s3-current.json"

      - name: Compile the current deployed version
        run: |
          VERSION=$(cat s3-current.json | jq '.version' |  tr -d '"')
          HASH=$(cat s3-current.json | jq '.hash' |  tr -d '"')
          echo ${VERSION} ${HASH}
          git checkout ${HASH}
          sed -i "s/.*version:.*/  version: \"${VERSION}\",/" mix.exs
          mix deps.get
          mix compile
          mix assets.deploy
          mix release
          echo "Return to the current branch head: ${GITHUB_SHA}"
          git checkout ${GITHUB_SHA}

      - name: Update project mix version
        run: |
          sed -i "s/.*version:.*/  version: \"${{ inputs.tag }}\",/" mix.exs

      - name: Create Release file version
        run: |
          echo "{\"version\":\"${{ inputs.tag }}\",\"hash\":\"${GITHUB_SHA}\"}" | jq > current.json

      - name: Install Elixir dependencies
        run: mix do deps.get, compile

      - name: Assets Deploy
        run: mix assets.deploy

      - name: Generate a Release
        run: mix release

      - name: 'Upload release file artifact'
        uses: actions/upload-artifact@v4
        with:
          name: release-file
          path: _build/prod/calori-${{ inputs.tag }}.tar.gz
          retention-days: 5

      - name: 'Upload version file artifact'
        uses: actions/upload-artifact@v4
        with:
          name: version-file
          path: current.json
          retention-days: 5

  upload_aws:
    name: Upload files to AWS environment
    needs: build
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - name: Download version file artefact
        uses: actions/download-artifact@v4
        with:
          name: version-file

      - name: Download release file artefact
        uses: actions/download-artifact@v4
        with:
          name: release-file

      - name: Copy a release file to the s3 distribution folder
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "sa-east-1"
          source: "_build/prod/calori-${{ inputs.tag }}.tar.gz"
          dest: "s3://calori-${{ secrets.CLOUD_ENV_NAME }}-distribution/dist/calori/calori-${{ inputs.tag }}.tar.gz"

      - name: Copy a version file to the s3 version folder
        uses: prewk/s3-cp-action@v2
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: "sa-east-1"
          source: "current.json"
          dest: "s3://calori-${{ secrets.CLOUD_ENV_NAME }}-distribution/versions/calori/${{ secrets.CLOUD_ENV_NAME }}/current.json"

  upload_gcp:
    name: Upload files to GCP environment
    needs: build
    runs-on: ubuntu-20.04
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Download version file artefact
        uses: actions/download-artifact@v4
        with:
          name: version-file

      - name: Download release file artefact
        uses: actions/download-artifact@v4
        with:
          name: release-file

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - id: 'upload-release-file'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'calori-${{ inputs.tag }}.tar.gz'
          destination: "calori-${{ secrets.CLOUD_ENV_NAME }}-distribution/dist/calori"
          process_gcloudignore: false

      - id: 'upload-version-file'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'current.json'
          destination: "calori-${{ secrets.CLOUD_ENV_NAME }}-distribution/versions/calori/${{ secrets.CLOUD_ENV_NAME }}"
          process_gcloudignore: false